empty file check added

diff --git a/bbx/run/default b/bbx/run/default
--- a/bbx/run/default
+++ b/bbx/run/default
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-echoerr() { echo "$@" 1>&2; }
-
 #check if file exists
+if [ ! -f /bbx/input/assembler.yaml ]
+then
+    printf 'No input data found at: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+fi
+
+#check if file is empty
+if [ ! -s /bbx/input/assembler.yaml ]
+then
+    printf 'Unable to parse: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+fi
+
 if [ ! -f /bbx/input/assembler.yaml ]
 then
     printf 'No input data found at: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
